### PR TITLE
Fixed bug and added icons

### PR DESCRIPTION
**Pull request by pfruh**
I fixed a bug, where the wrong bat file was executed for msys2, I also added Icons to the shortcuts

### CODE REVIEW

**Comment by njzhangyifei** [comment]
Oh nice. Thank you for the bug fix.

For the icons, I don't think I have a mingw64.exe or mingw32.exe in my MSYS2 directory. Would you please change those to msys2.ico (or provide a icon that we could use)?

**Comment by pfruh** [comment]
Are you on the current version? I updated everything with "pacman -Syuu" and those files got created.
They are part of the msys2-launchers package, which was installed by default.
https://github.com/elieux/msys2-launcher

**Comment by njzhangyifei** [comment]
I did a upgrade but I still didn't get those files. I have to do a manual install for this package to get these files and I don't know why.

Anyway, it's totally cool to have icons. Thanks!

**Comment by ghost** [comment]
@Kaeltis @njzhangyifei 
It seems need manual install this msys2-launchers package and can not using pacman to install it?
I didn't search it in the pacman.

**Comment by njzhangyifei** [comment]
@Neroldy It's on pacman, you could install it via `pacman -S msys/msys2-launcher-git`. I was saying that `msys2-launcher` doesn't come with my install of msys2 (so I have to manually install it via pacman). 

If it doesn't appear on your `pacman -Ss launcher`, you should synchronize your package database by `pacman -Sy`.

**Comment by ghost** [comment]
@njzhangyifei 
Oh, thanks~

**Comment by ghost** [comment]
@njzhangyifei Suggest use mingw64.exe first instead of mingw64_shell.bat in the mingw64_here.bat. Today I update the msys2 and there is only msys2_shell.cmd. So I think maybe use the default package mingw64.exe will be more "stable" ?

**Comment by njzhangyifei** [comment]
@Neroldy please refer to issue #7

**Pull request merged**
